Repository kubevirt/ansible-kubevirt-modules, pull requests merged in 2018-11, with the labels that each got.

#124 e2e test update
  tests/playbooks/e2e.yaml
Labels: size/L

#115 Add kubevirt_vm module
  README.md
  lib/ansible/modules/clustering/kubevirt/kubevirt_vm.py
Labels: size/L

#128 Add contributing guidelines
  CONTRIBUTING.md
Labels: reviews/2, size/XS

#130 Add sample playbook with a simple service definition
  tests/playbooks/k8s_service.yml
Labels: reviews/1, size/S

#132 readme: Minor fixes for typo and link
  README.md
Labels: size/XS

#129 Improve merge dict so it works with nested dict
  lib/ansible/modules/clustering/kubevirt/kubevirt_vm.py
  tests/units/modules/clustering/kubevirt/test_kubevirt_vm.py
Labels: reviews/2, size/M

#136 Add a dedicated module for managing Services
  lib/ansible/modules/clustering/kubevirt/k8s_service.py
  tests/playbooks/k8s_service.yml
Labels: reviews/2, size/L

#135 kubvirt_vm: Add support for networks & interfaces
  .gitignore
  lib/ansible/modules/clustering/kubevirt/kubevirt_vm.py
  tests/playbooks/kubevirt_vm_multus.yml
  tests/units/modules/clustering/kubevirt/test_kubevirt_vm.py
Labels: reviews/2, size/L

#142 kubevirt_vm: add simplified cloud-init definition
  lib/ansible/modules/clustering/kubevirt/kubevirt_vm.py
Labels: reviews/2, size/M

#134 Unify configs in sample playbooks; fix kubevirt account
  tests/kubevirt_rsa
  tests/kubevirt_rsa.pub
  tests/playbooks/kubevirt_raw_template.yml
  tests/playbooks/kubevirt_raw_vm.yml
  tests/playbooks/kubevirt_raw_vmi.yml
  tests/playbooks/kubevirt_raw_vmi_from_preset.yml
  tests/playbooks/kubevirt_raw_vmirs.yml
  tests/test_rsa
  tests/test_rsa.pub
Labels: reviews/1, size/L

#139 kubevirt_vm: structure returned k8s objects differently
  lib/ansible/modules/clustering/kubevirt/kubevirt_vm.py
  tests/units/modules/clustering/kubevirt/test_kubevirt_vm.py
Labels: reviews/2, size/S

#143 Simplify volumes & disks
  lib/ansible/modules/clustering/kubevirt/kubevirt_vm.py
Labels: reviews/2, size/L

#147 Remove kubevirt_raw module
  README.md
  lib/ansible/modules/clustering/kubevirt/kubevirt_raw.py
  tests/playbooks/e2e.yaml
  tests/playbooks/k8s_pvc.yml
  tests/playbooks/k8s_pvc_remove.yml
  tests/playbooks/k8s_remove.yml
  tests/playbooks/k8s_template.yml
  tests/playbooks/k8s_vm.yml
  tests/playbooks/k8s_vmi.yml
  tests/playbooks/k8s_vmi_from_preset.yml
  tests/playbooks/k8s_vmipreset.yml
  tests/playbooks/k8s_vmirs.yml
  tests/playbooks/kind_crud.yml
  tests/playbooks/kubevirt_vm_status.yml
  tests/units/modules/clustering/kubevirt/test_kubevirt_definition.py
  tests/units/modules/clustering/kubevirt/test_kubevirt_vm.py
Labels: reviews/2, size/L

#149 updated README.md
  README.md
Labels: size/S

#140 Added expose and ssh for e2e playbook
  tests/playbooks/e2e.yaml
  tests/playbooks/k8s_remove.yml
Labels: reviews/1, size/M
