Repository kubevirt/ansible-kubevirt-modules, pull requests merged in 2018-12, with the labels that each got.

#152 Template for issue and pull request
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: reviews/2, size/M

#155 Fixed: an example for NetworkAttachmentDefinition
  tests/playbooks/kubevirt_vm_multus.yml
Labels: reviews/2, size/S

#158 Don't use volumes in kubevirt_vm
  lib/ansible/modules/clustering/kubevirt/kubevirt_vm.py
  tests/playbooks/kubevirt_vm_multus.yml
Labels: size/S

#160 Update ansible.cfg
  tests/ansible.cfg
Labels: size/XS

#161 Document proper cniVersion to use with multus
  tests/playbooks/kubevirt_vm_multus.yml
Labels: size/XS

#150 Rename registryDisk to containerDisk
  lib/ansible/modules/clustering/kubevirt/kubevirt_rs.py
  lib/ansible/modules/clustering/kubevirt/kubevirt_vm.py
  tests/playbooks/k8s_template.yml
  tests/playbooks/k8s_vm.yml
  tests/playbooks/k8s_vmi.yml
  tests/playbooks/k8s_vmi_from_preset.yml
  tests/playbooks/k8s_vmirs.yml
  tests/playbooks/kind_crud.yml
  tests/playbooks/kubevirt_vm_multus.yml
Labels: reviews/2, size/L

#163 k8s_service: sync code with upstream PR
  lib/ansible/modules/clustering/kubevirt/k8s_service.py
Labels: size/L

#165 k8s_service: compat fix for older ansible
  lib/ansible/modules/clustering/kubevirt/k8s_service.py
Labels: reviews/2, size/S

#167 playbooks: fix race in waiting-for-CDI tasks
  tests/playbooks/e2e.yaml
  tests/playbooks/k8s_pvc.yml
Labels: reviews/1, size/XS
