Repository kubevirt/ansible-kubevirt-modules, pull requests merged in 2018-10, with the labels that each got.

#108 Externalize common test code
  tests/units/modules/clustering/kubevirt/test_kubevirt_scale_vmirs.py
  tests/units/modules/clustering/kubevirt/test_kubevirt_vm_status.py
  tests/units/modules/clustering/kubevirt/utils.py
Labels: size/M

#107 Re-add KubeVirtVM() tests with dynamic client
  tests/units/modules/clustering/kubevirt/test_kubevirt_raw.py
Labels: size/M

#110 Use 'wait_timeout' instead of 'wait' arg
  lib/ansible/modules/clustering/kubevirt/kubevirt_raw.py
  tests/playbooks/e2e.yaml
  tests/playbooks/kubevirt_raw_pvc.yml
Labels: size/XS

#109 Unify exception handling across modules
  lib/ansible/modules/clustering/kubevirt/kubevirt_raw.py
  lib/ansible/modules/clustering/kubevirt/kubevirt_scale_vmirs.py
  lib/ansible/modules/clustering/kubevirt/kubevirt_vm_status.py
Labels: size/M

#111 Use ansible 2.7.0+, since it's out
  requirements-dev.txt
Labels: size/XS

#112 Handle 'merge_type' var as required
  lib/ansible/modules/clustering/kubevirt/kubevirt_raw.py
Labels: size/XS

#114 Fix wait codepath in KubeVirtVM and add tests for it
  lib/ansible/modules/clustering/kubevirt/kubevirt_raw.py
  tests/units/modules/clustering/kubevirt/test_kubevirt_raw.py
Labels: size/M

#119 Some corrections for flake8
  .travis.yml
  setup.cfg
Labels: size/XS

#122 add venv to gitignore
  .gitignore
Labels: size/XS

#118 Unify (some) resource names in sample playbooks
  tests/playbooks/kubevirt_facts_vmipreset.yml
  tests/playbooks/kubevirt_facts_vmirs.yml
  tests/playbooks/kubevirt_scale_vmirs.yml
Labels: size/S

#117 Expand test coverage for scaling module
  tests/units/modules/clustering/kubevirt/test_kubevirt_raw.py
  tests/units/modules/clustering/kubevirt/test_kubevirt_scale_vmirs.py
  tests/units/modules/clustering/kubevirt/utils.py
Labels: size/L

#127 Fix facts playbooks and rename them to k8s_facts
  tests/playbooks/k8s_facts.yml
  tests/playbooks/k8s_facts_pvc.yml
  tests/playbooks/k8s_facts_template.yml
  tests/playbooks/k8s_facts_vm.yml
  tests/playbooks/k8s_facts_vmi.yml
  tests/playbooks/k8s_facts_vmipreset.yml
  tests/playbooks/k8s_facts_vmirs.yml
Labels: size/S
