Repository kubevirt/ansible-kubevirt-modules, pull requests merged in 2019-01, with the labels that each got.

#168 Bump min openshift rest client lib ver
  lib/ansible/modules/clustering/kubevirt/k8s_service.py
  lib/ansible/modules/clustering/kubevirt/kubevirt_preset.py
  lib/ansible/modules/clustering/kubevirt/kubevirt_rs.py
  lib/ansible/modules/clustering/kubevirt/kubevirt_vm.py
  lib/ansible/utils/module_docs_fragments/kubevirt_common_options.py
  requirements-dev.txt
Labels: reviews/2, size/S

#170 Make kubevirt modules work with api v1alpha3
  lib/ansible/module_utils/kubevirt.py
Labels: size/S

#171 python 3 fix
  lib/ansible/modules/clustering/kubevirt/kubevirt_vm.py
Labels: size/XS
