Repository kubevirt/ansible-kubevirt-modules, pull requests merged in 2019-06, with the labels that each got.

#243 Better logging + test multiple ansible versions
  automation/test.sh
  cluster/up.sh
  tests/playbooks/all.yml
Labels: size/S

#245 Add affinity parameters to app_deployment role
  roles/app_deployment/README.md
  roles/app_deployment/examples/deploy.yml
  roles/app_deployment/tasks/vms.yml
  tests/roles/deploy.yml
Labels: size/M

#244 Add vm_image role
  roles/vm_image/README.md
  roles/vm_image/examples/example1.yml
  roles/vm_image/examples/example2.yml
  roles/vm_image/tasks/main.yml
  roles/vm_image/tasks/pvc.yml
  roles/vm_image/templates/cdi_source.j2
Labels: size/L

#247 Disable tests of known broken modules
  tests/playbooks/all.yml
Labels: size/XS

#248 Fix upload task when source: not defined
  roles/vm_image/tasks/pvc.yml
Labels: size/XS

#238 Add network policy specification
  roles/app_deployment/README.md
  roles/app_deployment/defaults/main.yml
  roles/app_deployment/examples/network_policy.yml
  roles/app_deployment/tasks/main.yml
  roles/app_deployment/templates/network_policies.j2
  tests/roles/deploy.yml
Labels: size/L

#249 Dynamic test skipping based on issues status
  tests/playbooks/all.yml
  tests/playbooks/e2e.yaml
  tests/playbooks/known_issues.yaml
  tests/playbooks/known_issues/github.yaml
  tests/playbooks/kubevirt_dv_vm.yaml
  tests/playbooks/kubevirt_preset.yml
  tests/playbooks/kubevirt_pvc.yml
  tests/playbooks/kubevirt_vm.yml
  tests/playbooks/kubevirt_vmir.yml
Labels: size/M

#252 Jenkins: test all three ansible streams
  automation/install-ansible.sh
  automation/test.sh
Labels: size/M

#253 Travis: re–add role tests to the matrix
  .travis.yml
Labels: size/S

#254 Add topology_key to affinity tests and examples
  roles/app_deployment/examples/deploy.yml
  tests/roles/deploy.yml
Labels: size/XS

#256 Fix Markdown table syntax in Readme
  roles/app_deployment/README.md
Labels: size/XS

#257 Update Readme of app_deployment role
  roles/app_deployment/README.md
Labels: size/M

#259 Add cloud_init example for app_deploy role
  roles/app_deployment/examples/deploy.yml
Labels: size/XS

#250 Move non-test playbooks into examples/ dir
  examples/playbooks/k8s_auth.yaml
  examples/playbooks/k8s_facts.yaml
  examples/playbooks/k8s_facts_pvc.yaml
  examples/playbooks/k8s_facts_template.yaml
  examples/playbooks/k8s_facts_vm.yaml
  examples/playbooks/k8s_facts_vmi.yaml
  examples/playbooks/k8s_facts_vmipreset.yaml
  examples/playbooks/k8s_facts_vmirs.yaml
  examples/playbooks/k8s_remove.yaml
  examples/playbooks/k8s_service.yaml
  examples/playbooks/k8s_template.yaml
  examples/playbooks/k8s_vm.yaml
  examples/playbooks/k8s_vmi.yaml
  examples/playbooks/k8s_vmi_from_preset.yaml
  examples/playbooks/k8s_vmipreset.yaml
  examples/playbooks/k8s_vmirs.yaml
  examples/playbooks/kind_crud.yaml
  examples/playbooks/kubevirt_pvc_img_upload.yaml
  examples/playbooks/kubevirt_scale_vmirs.yaml
  examples/playbooks/kubevirt_vm_multus.yaml
  examples/playbooks/kubevirt_vm_status.yaml
  tests/playbooks/README.md
Labels: size/XS

#260 stable-2.8 no longer has the pvc regression
  tests/playbooks/known_issues.yaml
Labels: size/XS

#241 Add hostname and subdomain to app_deployment role
  roles/app_deployment/README.md
  roles/app_deployment/tasks/vms.yml
  tests/roles/deploy.yml
Labels: size/XS

#262 Workaround for travis+minikube instability
  tests/playbooks/known_issues.yaml
  travis/print-debug-info.sh
  travis/run-cluster.sh
Labels: size/S

#266 README: add high level info about CI testing
  README.md
Labels: size/S
