Repository kubevirt/ansible-kubevirt-modules, pull requests merged in 2019-07, with the labels that each got.

#267 Add CI testing of vm_image role
  .travis.yml
  tests/roles/all.yml
  tests/roles/app_deployment.yml
  tests/roles/vm_image.yml
Labels: size/S

#264 Jenkins: switch to openshift 3
  jenkins/check-patch.os-3.11.0.mounts
  jenkins/check-patch.os-3.11.0.packages
  jenkins/check-patch.os-3.11.0.sh
  jenkins/cluster-sync.sh
  jenkins/test.sh
  jenkins/tests.bats
  stdci.yaml
  tests/playbooks/all.yml
  tests/playbooks/known_issues.yaml
  tests/playbooks/kubevirt_template.yaml
Labels: size/M

#258 Update app_deployment role README.md
  roles/app_deployment/README.md
Labels: size/M

#268 Move blog post examples to this repo
  examples/blog/README.md
  examples/blog/part1/01_vm1_running.yaml
  examples/blog/part1/02_vm1.yaml
  examples/blog/part1/03_vm1_absent.yaml
Labels: size/M

#269 Files for blog post part 2
  examples/blog/part2/ansible.cfg
  examples/blog/part2/kubevirt.yaml
  examples/blog/part2/pvc.yaml
  examples/blog/part2/pvc_cdi.yaml
Labels: size/M

#235 Update Readme.md
  README.md
Labels: size/L

#270 readme reorg and partial rewrite
  README.md
Labels: size/L

#272 Drop pvc cloning and obsolete known issues
  tests/playbooks/known_issues.yaml
  tests/playbooks/kubevirt_pvc.yml
Labels: size/S

#273 Result method might from now on also be 'apply'
  tests/playbooks/kubevirt_dv_vm.yaml
  tests/playbooks/kubevirt_template.yaml
  tests/playbooks/kubevirt_vm.yml
Labels: size/S
