Repository kubevirt/ansible-kubevirt-modules, pull requests merged in 2019-02, with the labels that each got.

#175 Add k8s_auth from upstream PR
  lib/ansible/modules/clustering/kubevirt/k8s_auth.py
  tests/playbooks/k8s_auth.yml
Labels: size/L

#179 Added ansible.log to gitignore
  .gitignore
Labels: size/XS

#173 Add api version detection logic
  lib/ansible/module_utils/kubevirt.py
  lib/ansible/modules/clustering/kubevirt/kubevirt_preset.py
  lib/ansible/modules/clustering/kubevirt/kubevirt_rs.py
  lib/ansible/modules/clustering/kubevirt/kubevirt_vm.py
  tests/units/modules/clustering/kubevirt/test_kubevirt_preset.py
  tests/units/modules/clustering/kubevirt/test_kubevirt_scale_rs.py
  tests/units/modules/clustering/kubevirt/test_kubevirt_vm.py
Labels: size/L

#180 Fixed e2e playbook
  tests/playbooks/e2e.yaml
Labels: size/L

#169 Add template module
  lib/ansible/module_utils/kubevirt.py
  lib/ansible/modules/clustering/kubevirt/kubevirt_preset.py
  lib/ansible/modules/clustering/kubevirt/kubevirt_rs.py
  lib/ansible/modules/clustering/kubevirt/kubevirt_template.py
  lib/ansible/modules/clustering/kubevirt/kubevirt_vm.py
Labels: size/L

#182 Limit reqs to openshift client <0.9.0
  requirements-dev.txt
Labels: reviews/1, size/XS

#181 Make api detection logic python2 compatible
  lib/ansible/module_utils/kubevirt.py
  tests/units/modules/clustering/kubevirt/test_kubevirt.py
Labels: size/M

#185 Add cpu_cores parameter
  lib/ansible/module_utils/kubevirt.py
  lib/ansible/modules/clustering/kubevirt/kubevirt_vm.py
  lib/ansible/utils/module_docs_fragments/kubevirt_common_options.py
  tests/playbooks/e2e.yaml
Labels: size/S

#183 Fix cloud-init to work with version v1alpha3
  lib/ansible/module_utils/kubevirt.py
  lib/ansible/modules/clustering/kubevirt/kubevirt_vm.py
Labels: size/XS

#190 Fix disk and volumes creation
  lib/ansible/module_utils/kubevirt.py
Labels: size/XS

#191 Fix interfaces and networks creation
  lib/ansible/module_utils/kubevirt.py
Labels: size/XS

#193 Small tests fixes
  tests/playbooks/k8s_facts_vm.yml
  tests/playbooks/kubevirt_preset.yml
Labels: size/XS

#196 Fix execute unit tests before integration test
  .travis.yml
  test.sh
Labels: size/S

#195 Reduce the disk and memory size for e2e
  tests/playbooks/e2e.yaml
Labels: reviews/1, size/XS

#197 Make this repo to hold only tests
  .travis.yml
  CONTRIBUTING.md
  README.md
  defaults/main.yml
  lib/ansible/module_utils/kubevirt.py
  lib/ansible/modules/clustering/kubevirt/k8s_auth.py
  lib/ansible/modules/clustering/kubevirt/k8s_service.py
  lib/ansible/modules/clustering/kubevirt/kubevirt_preset.py
  lib/ansible/modules/clustering/kubevirt/kubevirt_rs.py
  lib/ansible/modules/clustering/kubevirt/kubevirt_template.py
  lib/ansible/modules/clustering/kubevirt/kubevirt_vm.py
  lib/ansible/utils/module_docs_fragments/kubevirt_common_options.py
  lib/ansible/utils/module_docs_fragments/kubevirt_vm_options.py
  meta/main.yml
  tasks/main.yml
  test.sh
  tests/playbooks/all.yml
  tests/playbooks/kubevirt_preset.yml
  tests/playbooks/kubevirt_vmir.yml
  tests/units/conftest.py
  tests/units/modules/clustering/kubevirt/test_kubevirt.py
  tests/units/modules/clustering/kubevirt/test_kubevirt_definition.py
  tests/units/modules/clustering/kubevirt/test_kubevirt_preset.py
  tests/units/modules/clustering/kubevirt/test_kubevirt_scale_rs.py
  tests/units/modules/clustering/kubevirt/test_kubevirt_vm.py
  tests/units/modules/clustering/kubevirt/utils.py
Labels: size/XXL

#200 Update ansible.cfg
  tests/ansible.cfg
Labels: size/XS

#201 Switch k8s_auth.yml to using module defaults
  tests/playbooks/k8s_auth.yml
Labels: reviews/1, size/S

#202 Info on using kubevirt_cdi_upload module
  README.md
  tests/playbooks/kubevirt_pvc_img_upload.yml
Labels: reviews/1, size/S

#203 Update all kubevirt.io apivers to v1alpha3
  tests/playbooks/k8s_facts.yml
  tests/playbooks/k8s_facts_vm.yml
  tests/playbooks/k8s_facts_vmi.yml
  tests/playbooks/k8s_facts_vmipreset.yml
  tests/playbooks/k8s_facts_vmirs.yml
  tests/playbooks/k8s_remove.yml
  tests/playbooks/k8s_template.yml
  tests/playbooks/k8s_vm.yml
  tests/playbooks/k8s_vmi.yml
  tests/playbooks/k8s_vmi_from_preset.yml
  tests/playbooks/k8s_vmipreset.yml
  tests/playbooks/k8s_vmirs.yml
  tests/playbooks/kind_crud.yml
Labels: size/M

#205 Remove volumeName from tests
  tests/playbooks/k8s_template.yml
  tests/playbooks/k8s_vm.yml
  tests/playbooks/k8s_vmi.yml
  tests/playbooks/k8s_vmi_from_preset.yml
  tests/playbooks/k8s_vmirs.yml
  tests/playbooks/kind_crud.yml
Labels: size/M

#206 Revert "Update ansible.cfg"
  tests/ansible.cfg
Labels: size/XS
