Repository kubevirt/ansible-kubevirt-modules, pull requests merged in 2019-05, with the labels that each got.

#226 Update kubevirt_pvc.yml
  tests/playbooks/kubevirt_pvc.yml
Labels: size/XS

#225 DataVolume example
  tests/playbooks/all.yml
  tests/playbooks/kubevirt_dv_vm.yaml
Labels: size/M

#228 Fix the failing check
  tests/playbooks/kubevirt_dv_vm.yaml
Labels: size/XS

#233 Enabled Data volumes
  test.sh
Labels: size/XS

#230 Add app_deployment role
  roles/app_deployment/README.md
  roles/app_deployment/examples/deploy.yml
  roles/app_deployment/tasks/main.yml
  roles/app_deployment/tasks/vms.yml
  roles/app_deployment/templates/deployment.j2
  roles/app_deployment/templates/service.j2
  test.sh
  tests/roles/deploy.yml
  tests/roles/roles
Labels: size/L

#229 Added example for Inventory plugin
  tests/ansible.cfg
  tests/playbooks/kubevirt_vm_multus.yml
  tests/playbooks/plugin/kubevirt.yaml
  tests/playbooks/plugin/touch-vmi.yaml
Labels: size/M

#234 Changes for better automation tests
  tests/playbooks/e2e.yaml
Labels: size/S

#237 Added example for Templates and VM from templates
  tests/playbooks/kubevirt_template.yaml
Labels: size/M

#236 Add openshift3 jenkins target support
  .gitignore
  automation/check-patch.os-3.11.0.mounts
  automation/check-patch.os-3.11.0.packages
  automation/check-patch.os-3.11.0.sh
  cluster/common.sh
  cluster/sync.sh
  cluster/up.sh
Labels: size/M
