Repository kubevirt/ansible-kubevirt-modules, pull requests merged in 2019-03, with the labels that each got.

#204 Drop cdi_upload module along with all module code
  lib/ansible/module_utils/__init__.py
  lib/ansible/module_utils/kubevirt.py
  lib/ansible/modules/clustering/kubevirt/__init__.py
  lib/ansible/modules/clustering/kubevirt/kubevirt_cdi_upload.py
  lib/ansible/utils/module_docs_fragments/kubevirt_common_options.py
  lib/ansible/utils/module_docs_fragments/kubevirt_vm_options.py
  tests/ansible.cfg
Labels: size/XL

#208 Add info how to use KubeVirt inv plugin
  README.md
Labels: size/M

#207 Update playbooks to use kubevirt_pvc module
  tests/playbooks/all.yml
  tests/playbooks/e2e.yaml
  tests/playbooks/k8s_pvc.yml
  tests/playbooks/k8s_pvc_remove.yml
  tests/playbooks/kubevirt_pvc.yml
  tests/playbooks/kubevirt_pvc_img_upload.yml
Labels: reviews/1, size/L

#209 Switch to 'wait: yes' for PVCs
  tests/playbooks/kubevirt_pvc.yml
  tests/playbooks/kubevirt_pvc_img_upload.yml
Labels: reviews/1, size/M

#210 Use module_defaults feature
  tests/playbooks/e2e.yaml
Labels: size/S

#211 Update storageClassName to be used for QE env
  tests/playbooks/e2e.yaml
Labels: size/XS

#213 Add PR_NUMBER env var
  .travis.yml
Labels: size/XS

#215 Switch to 'wait: yes' for PVCs, part 2
  tests/playbooks/e2e.yaml
Labels: reviews/1, size/S

#217 Add pvc cloning to kubevirt_pvc.yml
  tests/playbooks/kubevirt_pvc.yml
Labels: reviews/1, size/S
